services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  javalin-api:
    image: mcducker/javalin-api-pipeline:latest
    container_name: javalin-api
    restart: unless-stopped
    ports:
      - "7777:7777"
    depends_on:
      -db